name: "Basic"
on:
  push
jobs:
  download_and_run:
    runs-on: ubuntu-latest
#    continue-on-error: true
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: start code
        run: python programm.py

  test_sintax:
    runs-on: ubuntu-latest
    needs: download_and_run
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: 'Run PEP8'
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'




