name: "Basic"
on:
  push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Stage1
        run: ls -la
      - name: Download code
        uses: actions/checkout@v3
      - name: Stage2
        run: ls -la
      - name: install dependences
        run: pip install tk
      - name: start code
        run: python programm.py

