name: "Basic"
on:
  push
jobs:
  download_and_run:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest]
        python_version: [3.7, 3.8]
    runs-on: ${{ matrix.os}}
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python_version}}
      - name: start code
        run: python programm.py

  test_sintax:
    runs-on: ubuntu-latest
    needs: download_and_run
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: 'Run PEP8'
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'




